project 'BaseFoundation.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BaseFoundation' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BaseFoundation
  pod 'ReactiveCocoa'
  
  target 'BaseFoundationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BaseFoundationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
